services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    container_name: phishing_api
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile.ui
    container_name: phishing_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
